language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

branches:
  except:
  - gh-pages

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local_dir: public
#  keep-history: true
#  only:
#    branch: master

before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run build"
  - "npm run lint"
# after_success:
#  - "npm run deploy"

notifications:
  email: true

jobs:
  include:
   - name: 'Publish branch to Chromatic'
     if: branch != main 
     script: npm run chromatic -- --project-token=${CHROMATIC_PROJECT_TOKEN}
   - name: 'Publish to Chromatic & auto-accept changes on main branch'
     if: branch = main
     script: npm run chromatic -- --project-token=${CHROMATIC_PROJECT_TOKEN} --auto-accept-changes
