language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules

branches:
  only:
  - master

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  local_dir: public
#  keep-history: true
#  only:
#    branch: master

before_script:
  - "npm i -g gatsby --legacy-peer-deps"
  - "npm i --legacy-peer-deps"
script:
  - "npm run build"
  - "npm run lint"
#after_success:
#  - "npm run deploy"

notifications:
  email: true
